title: Bisq
url: "https://bisq.io"
markdown: kramdown
permalink: /blog/:title/
livereload: true
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
defaults:
  - scope:
      path: ""
    values:
      sitemap: false
feed:
  path: blog/feed.atom
include:
  - _redirects
exclude:
  - CNAME
  - README
  - Gemfile
